const express = require("express");
const router = express.Router();
const operationController = require("../controllers/operationController");
const protect = require("../middleware/authMiddleware");
const validate = require("../middleware/validationMiddleware");
const operationSchema = require("../validators/operationValidator");
router.post("/add", protect, validate(operationSchema), operationController.add);
router.post("/subtract", protect, validate(operationSchema), operationController.subtract);
router.post("/multiply", protect, validate(operationSchema), operationController.multiply);
router.post("/divide", protect, validate(operationSchema), operationController.divide);
router.post("/compare", protect, validate(operationSchema), operationController.compare);
router.post("/convert", protect, validate(operationSchema), operationController.convert);
router.post("/add-with-target-unit", protect, validate(operationSchema), operationController.addWithTargetUnit);
router.post("/subtract-with-target-unit", protect, validate(operationSchema), operationController.subtractWithTargetUnit);
router.get("/history/type/:type", protect, operationController.getHistoryByType);
router.get("/history/operation/:operation", protect, operationController.getHistoryByOperation);
router.get("/history/errored", protect, operationController.getErroredHistory);
router.get("/count/:operation", protect, operationController.getOperationCount);
module.exports = router;